title: Conference Deadlines
description: Countdowns to IC-Design, Power Electronics, Electrical Drives and Electronic Design Automation Conference Deadlines
author: Electronics & Drives

#domain: ""
domain: "electronics-and-drives.github.io"
baseurl: "/conference-deadlines"

twitter_hashtag: EandD
github_username: electronics-and-drives
github_repo: conference-deadlines

markdown: kramdown
ga_id: ""

include: ['_pages']
